name: testbash pipeline
run-name: ${{ github.actor }} is at testbash
on: [push]
jobs:
  my-pipeline:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello testbash"
  run-api-tests:
    runs-on: ubuntu-latest
    needs: my-pipeline
    steps:
      - uses: actions/checkout@v2
      - name: run api test
        working-directory: src/api
        run: |
          npm install
          npm test
  run-e2e-tests:
    runs-on: ubuntu-latest
    needs: my-pipeline
    steps:
      - uses: actions/checkout@v2
      - name: run e2e tests
        working-directory: e2e
        run: |
          npm install
          npm test
